- name: Catalogue Setup
  hosts: all
  become: true
  tasks:
    - name: Install NodeJS 20
      ansible.builtin.dnf:
        name: '@nodejs:20'
        state: present

    - name: Add roboshop application user
      ansible.builtin.user:
        name: roboshop

    - name: Remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /app
        remote_src: yes

    - name: Install packages based on package.json.
      community.general.npm:
        path: /app

    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo


    - name: Install MognoDB Shell
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: Load Master Data
      ansible.builtin.shell: mongosh --host dev.mongodb.shkishore.online </app/db/master-data.js

    - name: Copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Start Catalogue service
      ansible.builtin.systemd_service:
        state: restarted
        name: catalogue
        enabled: true
        daemon_reload: true